In [1]:
import numpy as np
import pandas as pd

### Creating Numpy Arrays

In [2]:
# np.array
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# dtype
np.array([1,2,3],dtype=float) # bool,complex etc...

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2) # similar like python range()

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# np.ones and np.zero
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((3,4))

array([[0.74171955, 0.29301525, 0.05845097, 0.85059793],
       [0.90355263, 0.12361356, 0.09895151, 0.05161208],
       [0.47082333, 0.0895083 , 0.48336137, 0.41144576]])

In [10]:
# np.linspace
np.linspace(-10,10,10) # first=lower bound,second=upper bound,third= no. of elements


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# ndim
a.ndim # tells about dimensions of np.array

1

In [13]:
# shape
a.shape

(3,)

In [14]:
# size
a.size # tell total elements

3

In [15]:
# itemsize
a.itemsize # tell no of bytes of an element, like 64 bit integer is consists of 8 bytes

8

In [16]:
# dtype
a.dtype

dtype('int64')

### Changing Datatype

In [17]:
a

array([1, 2, 3])

In [18]:
a.dtype # check data type
a.astype(np.int32)

array([1, 2, 3], dtype=int32)

### Array Operation

In [19]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(1,13).reshape(3,4)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
# scalar operation

# arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational
a2>10 # <,>,>=,==,<=,!=


array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [22]:
# vector operation
# happens between vectors/tensors/Matrix
# arithmetic
a1/a2

array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286, 0.875     ],
       [0.88888889, 0.9       , 0.90909091, 0.91666667]])

In [23]:
np.round(a1/a2)

array([[0., 0., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# max/min/sum/prod
#axis -> 0 means columns and 1 means rows
print(np.max(a1))
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))
print(np.prod(a1))
a1

11
[ 8  9 10 11]
[ 3  7 11]
0


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
# mean/median/std/var
a1.mean() # axis is avaliable
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(11.916666666666666)

In [30]:
# trignometric function
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [35]:
# dot product
# Condition if we have dimension (x,y).(x1,y1) only possible if y=x1 
# and resultant shape would be (x,y1) 
a=np.arange(12).reshape(3,4)
a1=np.arange(12).reshape(4,3)
np.dot(a1,a2)

array([[ 23,  26,  29,  32],
       [ 68,  80,  92, 104],
       [113, 134, 155, 176],
       [158, 188, 218, 248]])

In [37]:
# log and exponents
np.log(a)
np.exp(a1) # ?


C:\Users\Muhammad\AppData\Local\Temp\ipykernel_13124\11775331.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [43]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)


array([[87., 35., 66.],
       [72., 37., 35.]])

### Indexing & Slicing

In [48]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(12).reshape(2,2,3)

In [45]:
a1[-1]

np.int64(9)

In [46]:
a2[1,2] # for picking a element from a matrix



np.int64(6)

In [55]:
print(a3)
a3[1][1][0]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


np.int64(9)

In [56]:
a1[2:5]

array([2, 3, 4])

In [70]:
print(a2)
a2[:,0] # this will take all rows and return first element of each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 4, 8])

In [73]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [84]:
a1[1:9:2] # this will skip one element and print next
a2[::2,::3] # give corner elements of "a2"
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [85]:
a2[1:2,::3]

array([[4, 7]])

In [87]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
a3[0,1,:]
a3[2,1:,1:]
a3[::2,:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Iterating
- same like python
- np.nditer avaliable

In [96]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [102]:
# transpose
np.transpose(a2)
a2.T # same as above

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [104]:
a2.ravel() # convert in 1d
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [107]:
# horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [108]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [110]:
# horizontal split
a6=np.hstack((a4,a5))
np.hsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [112]:
# vertical split
a6=np.vstack((a4,a5))
np.vsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]